name: ci

permissions: {}

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch: {}
  merge_group: {}

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node_version: 18
          cache: npm

      - name: 📦 Install dependencies
        run: npm install

      - name: 📝 Lint
        run: npm run lint
